name: Pipeline for Client Update Microservice

on:
  push:
    branches:
      - test
    paths:
      - 'client-update-service/**'
      - '.github/workflows/client-update-pipeline.yml'
  pull_request:
    branches: 
      - test
    paths:
      - 'client-update-service/**'
      - '.github/workflows/client-update-pipeline.yml'
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_UPDATE}}:latest ./client-update-service

      - name: Push Docker image to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_UPDATE}}:latest

  deploy-to-ec2-instance:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_TEST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Pull, stop, and redeploy the Docker container"
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_IMAGE_UPDATE}}:latest
            docker stop ${{secrets.DOCKER_IMAGE_UPDATE}}|| true
            docker rm ${{secrets.DOCKER_IMAGE_UPDATE}} || true
            docker run --restart always -e DATASOURCE_URL=${{secrets.DATASOURCE_URL}} \
                       -e DATASOURCE_PORT=${{secrets.DATASOURCE_PORT}} \
                       -e DATABASE=${{secrets.DATABASE}} \
                       -e DATASOURCE_USERNAME=${{secrets.DATASOURCE_USERNAME}} \
                       -e DATASOURCE_PASSWORD=${{secrets.DATASOURCE_PASSWORD}} \
                       -d --name ${{secrets.DOCKER_IMAGE_UPDATE}} \
                       -p 1032:1032 ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_UPDATE}}:latest